travis:
  secure:
    BINSTAR_TOKEN: Rjw7LD6/7z1FMCeJY3sNK3690zqFXHFck2KDo4dJ/qaLgr/DGqsjpumyRY0rqhvjIBX+oiNsGsHvH0tG4e5jJmEes1gAFk1FhF+I37yaaUO4J5KnpyGUnjDUuyp2/wbJ8tPivL9iTdnHk1erSwOR5+1WZFPDS9HaGmfRZ8xisSulWMg1+yQ6O7nn+luNoSaPXTpJ+E8WNJFGLETjq+beMaOPDx2vfC6i6g2MgNOPztntiReWfzADi4XlcCn/PIbf0ShVPYgKa2DgbBJd0WLCvUriXb9Ub59l0D0+jHqh712Y2M3fCL3c6pEIcdOCwMQ2xnioPdx6iGKIINs/Zl6XXb/D7wg+396FljvFEdVzrwR47VArj2L7SlgPWH3me8KjGGrm4NqI2Tuo5wYvDZN9bj4tdGTtjx4o6/W6pFIQBn24406riBrn0asaRhfvdXicRfM1SoAiRXaoM+jImyJBMGfLySjwmdo1D7FntYXyvYVburuCUWnQG55wvdXfO1QgC4muaXyfgicvKANWD7XtHz6aITnm0nwOG+Wk5UJKP7+zX3Et6y6FBsO8UAKcD0oSqiiXObVvBZB9tYomeZCiqhuOvUnWISbUHeTbythSwgGrMGaJwkbfLE6fZlYCZ4gfpmwrS1US6bWYYOlPKuxIR3Hrd1TZ+VBvJxr5sAbomCs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
